### ISSUE TITLE
Can't find the start_up folder after installing deepr-ai on Windows

### ISSUE THREAD

**Issue by RepoRascal** [Deepr-ai/Deepr-ai#3]
Hi there,

I recently installed deepr-ai on my Windows machine via pip, but I can't seem to find the start_up folder. I also tried building and installing deepr-ai from the source code, but the issue persists. Could you please provide some guidance on how to get started with deepr-ai and locate the start_up folder?

![C__Windows_System32_cmd exe-python-setup py-build-2023-03-01-19-40-08 (1)](https://user-images.githubusercontent.com/126687635/222174557-5a2b67d0-ca8a-4c4f-aa1a-8ba1bd73671c.gif)

![image](https://user-images.githubusercontent.com/126687635/222175310-4b245c7e-a720-425f-9964-4663f9220a9b.png)

** **
**i also tried installing via pip:**

![image](https://user-images.githubusercontent.com/126687635/222175934-34fa5a17-cc77-41e9-b1ed-64f6e7a2a031.png)

![image](https://user-images.githubusercontent.com/126687635/222176163-05a2f5f6-012e-461e-a4a4-e275716b5a59.png)

_I would appreciate any help or guidance you can provide. Thanks!_

**Comment by jvadair** [comment]
Hey @RepoRascal, sorry for the confusion.

At the moment, there is no `start_up` folder. Deepr_ai is still under development, and this folder has not yet been added.
However, there is some documentation in the works, available here: https://docs.deepr.dev/books/deeprai-docs

Although this doesn't appear to be a Windows-related problem, please bear in mind that support for Windows is still experimental, as @ArrowsGD and myself have limited access to Windows machines.

I will make a pull request to clarify the documentation, for the time being.
